from .client import CRMApiClient
from .models import (
    # Inputs
    ActionType,
    PaymentProvider,
    PaymentMethod,
    CreateUserInput,
    UpdateUserInput,
    AddAccessInput,
    PaymentsCalculateInput,
    InvoiceDraftInput,
    InvoiceIssueInput,
    RefundInput,
    # Accounts/Profile
    DayTotal,
    AccountItem,
    ProfileStatistics,
    PosterAccount,
    PosterSubscription,
    Bot3Summary,
    # Catalog/Departments/Dialogs/Notes
    ProductEntry,
    CategoryBucket,
    DepartmentItem,
    DialogItem,
    TransferDialogResult,
    StatusItem,
    StatusesResult,
    ChangeStatusResult,
    DialogSearchItem,
    DialogSearchResult,
    NoteItem,
    NoteStaff,
    # Payments
    CalcItem,
    PaymentsCalculateResult,
    InvoiceDraftResult,
    InvoiceIssueResult,
    ActivationLink,
    PaymentHistoryItem,
    PaymentsListResult,
    ConfirmPaymentResult,
    RefundResult,
    InvoiceInfoResult,
    Sale,
    MonthlySalesResult,
    # Prompt
    PromptUpdateResult,
    # Proxy
    ProxyCheckItem,
    ProxyCheckResult,
    ProxyItem,
    # Referrals
    ReferreePayment,
    ReferreeInfo,
    ReferralsInfoResult,
    # Servers
    ServerRestartResult,
    # Staff
    StaffInfo,
    # Users
    UserBotInfo,
    GetUserResult,
    CreateUserResult,
    UpdateUserResult,
    AddAccessResult,
    ExtendAccessResult,
    ExtendAiLimitResult,
    ListUserItem,
    ListUsersResult,
    # Subscriptions
    AccessPaymentRef,
    AccessStaffRef,
    AccessHistoryItem,
    SubscriptionsHistoryResult,
    AccessDefinitionsResult,
    TransferLinkResult,
    # Tasks
    TaskListItem,
    TaskInfoResult,
    TaskLogResult,
    ActiveTasksResult,
    # Sales decks (legacy ScriptItem / ScriptFull для list/get/create
    # удалены в Phase 5 — теперь это reply templates ниже).
    PriceMediaItem,
    ToolsMediaItem,
    ToolsMediaResult,
)
from .exceptions import (
    SDKError,
    ConfigError,
    AuthError,
    ApiError,
    HttpError,
    ValidationError,
)

__all__ = [
    # Client
    "CRMApiClient",
    # Inputs
    "ActionType",
    "PaymentProvider",
    "PaymentMethod",
    "CreateUserInput",
    "UpdateUserInput",
    "AddAccessInput",
    "PaymentsCalculateInput",
    "InvoiceDraftInput",
    "InvoiceIssueInput",
    "RefundInput",
    # Accounts/Profile
    "DayTotal",
    "AccountItem",
    "ProfileStatistics",
    "PosterAccount",
    "PosterSubscription",
    "Bot3Summary",
    # Catalog/Departments/Dialogs/Notes
    "ProductEntry",
    "CategoryBucket",
    "DepartmentItem",
    "DialogItem",
    "TransferDialogResult",
    "StatusItem",
    "StatusesResult",
    "ChangeStatusResult",
    "DialogSearchItem",
    "DialogSearchResult",
    "NoteItem",
    "NoteStaff",
    # Payments
    "CalcItem",
    "PaymentsCalculateResult",
    "InvoiceDraftResult",
    "InvoiceIssueResult",
    "ActivationLink",
    "PaymentHistoryItem",
    "PaymentsListResult",
    "ConfirmPaymentResult",
    "RefundResult",
    "InvoiceInfoResult",
    "Sale",
    "MonthlySalesResult",
    # Prompt
    "PromptUpdateResult",
    # Proxy
    "ProxyCheckItem",
    "ProxyCheckResult",
    "ProxyItem",
    # Referrals
    "ReferreePayment",
    "ReferreeInfo",
    "ReferralsInfoResult",
    # Servers
    "ServerRestartResult",
    # Staff
    "StaffInfo",
    # Users
    "UserBotInfo",
    "GetUserResult",
    "CreateUserResult",
    "UpdateUserResult",
    "AddAccessResult",
    "ExtendAccessResult",
    "ExtendAiLimitResult",
    "ListUserItem",
    "ListUsersResult",
    # Subscriptions
    "AccessPaymentRef",
    "AccessStaffRef",
    "AccessHistoryItem",
    "SubscriptionsHistoryResult",
    "AccessDefinitionsResult",
    "TransferLinkResult",
    # Tasks
    "TaskListItem",
    "TaskInfoResult",
    "TaskLogResult",
    "ActiveTasksResult",
    # Sales decks
    "PriceMediaItem",
    "ToolsMediaItem",
    "ToolsMediaResult",
    # Exceptions
    "SDKError",
    "ConfigError",
    "AuthError",
    "ApiError",
    "HttpError",
    "ValidationError",
]